pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '10.14.1'
  - script: yarn install
    displayName: Install dependencies
  - script: yarn build
    displayName: Build application
  - script: yarn test
    displayName: Running tests
