resources:
  containers:
    - container: mongo
      image: mongo
      ports:
        - 27017:27017

pool:
  vmImage: Ubuntu-16.04

services:
  mongo: mongo

steps:
  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: 10.14.1

  - script: yarn install
    displayName: Install dependencies

  - script: yarn build
    displayName: Build application

  - script: yarn test:ci
    displayName: Running tests

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: Test results for JavaScript
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
      reportDirectory: $(System.DefaultWorkingDirectory)/coverage

  - task: DeleteFiles@1
    inputs:
      sourceFolder: node_modules

  - script: yarn install --prod
    displayName: Install only production dependencies

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: $(System.DefaultWorkingDirectory)
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
