pool:
  vmImage: Ubuntu-16.04

steps:
  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: 10.14.1

  - script: yarn install
    displayName: Install dependencies

  - script: yarn build
    displayName: Build application

  - script: yarn test:ci
    displayName: Running tests

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/TEST-RESULTS.xml'
      testRunTitle: Test results for JavaScript
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
      reportDirectory: $(System.DefaultWorkingDirectory)/coverage

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: $(System.DefaultWorkingDirectory)
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
