[build]
  publish = "dist/app/"
  command = "yarn test:unit && yarn build"
  environment = { YARN_VERSION = "1.12.1" }
  functions = "dist/functions/"

[[redirects]]
  from = "https://api.cibulb.info/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]] 
    from = "/netlifytest/*" 
    to = "/.netlify/functions/:splat" 
    status = 200
